ecommerce/cartapp/urls.py
from django.urls import path,include
from. import views


app_name='cart'

urlpatterns = [
    path('add/<int:Product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:Product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:Product_id>/', views.cart_delete, name='cart_delete')

]

ecommerce/ecomapp/urls.py
from django.urls import path
from. import views
app_name='ecomapp'

urlpatterns = [
    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.Product, name='prod_cat'),

]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecomapp/',include('ecomapp.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/searchapp/urls.py
from django.urls import path
from  .import views

app_name='searchapp'

urlpatterns = [
    path('',views.searchresult,name='searchresult'),
]

ecommerce/cartapp/models.py
from django.db import models
from ecomapp.models import product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class Cart_item(models.Model):
    Product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='Cart_item'

    def sub_total(self):
        return self.Product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.Product)

class Caarrt_item(models.Model):
    Product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='Caarrt_item'

    def sub_total(self):
        return self.Product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.Product)

ecommerce/ecomapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='catergorys'

    def get_url(self):
        return reverse('ecomapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecomapp:prod_cat',args=[self.category.slug,self.slug])

    class meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/searchapp/models.py
from django.db import models

# Create your models here.

ecommerce/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart,Caarrt_item
from ecomapp.models import product
from django.core.exceptions import ObjectDoesNotExist


# Create your views here

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, Product_id):
    Product = product.objects.get(id=Product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = Caarrt_item.objects.get(Product=Product, cart=cart)
        if cart_item.quantity < cart_item.Product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Caarrt_item.DoesNotExist:
        cart_item = Caarrt_item.objects.create(
            Product=Product,
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = Caarrt_item.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.Product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, counter=counter, total=total))


def cart_remove(request,Product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    Product=get_object_or_404(product,id=Product_id)
    cart_item=Caarrt_item.objects.get(Product=Product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def cart_delete(request,Product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    Product=get_object_or_404(product,id=Product_id)
    cart_item=Caarrt_item.objects.get(Product=Product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce/ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from.models import category,product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here

def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def Product(request,c_slug,product_slug):
    try:
        Product=product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'Product': Product})

ecommerce/searchapp/views.py
from django.shortcuts import render
from ecomapp.models import product
from django.db.models import Q
# Create your views here.

def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
       query = request.GET.get('q')
       products = product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
       return render(request,'search.html',{'query':query,'products':products})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="descripton" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="{% static 'css/customs.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





    <script src="https://kit.fontawesome.com/21c419a9db.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block titile %} {% endblock %}</title>

</head>
<body class="bodyy">
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    <div class="bdy">
        {% block body %}
        {% endblock %}

    </div>
    {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

</div>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
cart page .place order
{% endblock %}
{% block title %}
cart
{% endblock %}
{% block body %}
<div class="textt">
{% if not cart_items %}
 <div>
     <div class="text-center">
         <br>
         <h1 class="text-center">
             your shopping cart is empty
         </h1>
         <br>
         <p class="text-center">
             please click <a href="{% url 'ecomapp:allprodcat' %}">here</a>to continue shopping
         </p>
     </div>
 </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">your shopping cart</h1>
        <br>
    </div>
    <div class="row">
        <div class="col=-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_customtable">
                <thead class="my_customthead">
                <tr>
                    <th colspan="5">
                        your items
                    </th>
                </tr>
                </thead>
                <tbody class="text-center">
                {% for cart_item in cart_items %}
                <tr>
                    <td class="text-center">
                      <img src = "{{cart_item.Product.image.url}}" alt="" class="float-center rounded custom_image" width="100px;" height="100px;"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.Product.name}}
                        <br>
                        sku:{{cart_item.Product.id}}
                        <br>
                        price:{{cart_item.Product.price}}
                        <br>
                        qty:{{cart_item.quantity}} X {{cart_item.Product.price}}
                    </td>
                    <td>
                        RS:{{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.Product.stock %}
                    <td>
                        &nbsp;<a href="{% url 'cart:add_cart' cart_item.Product.id %}" class="custom_a"><i class="fa-solid fa-square-plus"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.Product.id %}" class="custom_a"><i class="fa-solid fa-square-minus"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_delete' cart_item.Product.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>

                    </td>
                    {% else %}
                     <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.Product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_delete' cart_item.Product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>

                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>


    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_customtable">
          <thead class="my_customthead">
          <tr>
              <th>
                  checkout
              </th>
          </tr>
          </thead>
            <tbody>
            <tr>
                <td>
                    please review your shopping cart items before proceeding for order
                </td>
            </tr>
            <tr>
                <td class="text-center">
                    your total is RS : {{total}}
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecomapp:allprodcat' %}" class="btn btn-secondary">continue shopping</a><br><br>
            <a href="{% url 'ecomapp:allprodcat' %}" class="btn btn-secondary">make payment</a>

        </div>
    </div>
    </div>
</div>
     </div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{category.description|truncatewords:155}}
  {% else %}
    welcome to digital mart store
  {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
    {{category.name}}- digital mart
  {% else %}
    new collections
  {% endif %}
{% endblock %}

{% block body %}
  {% if category %}
    <div class="#">

        <p class="all"><a href="{% url 'ecomapp:allprodcat' %}">all product</a></p>
    </div>
    {% endif %}
 <div class="mx_auto">
   {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="100%" height="430">
 </div><br>
  <div>
      <h1 class="text-center my_title">{{category.name}}</h1>
<!--      <p class="text-justify">{{category.description}}</p>-->
  </div>
    {% else %}
 <div>
     <img class="imagebann"  src="{% static 'img/banner.png' %}" alt="ourproducts" width="100%" height="430">

 </div><br>
  <div class="our">
    <h1 class="text-center my_title"> our collections</h1>
    <p class="text-justify">In 1946, twelve albums by eleven artists topped Billboard's weekly chart of the best-selling albums in the United States. At the time, the chart was titled Best-Selling Popular Record Albums, and it collected sales data from United States-based record dealers, numbering at least 200 in January and increasing to over 4,000 by the end of the year. The first chart-topper was Merry Christmas</p>
  </div>
    {% endif %}
  <div class="container">
      <div class="row">
      {% for product in products.object_list %}
      <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
          <div class="card h-100 text-center" style="min-width:18rem;">
               <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}"></a>
              <div class="card-body ">
                  <h4>{{product.name}}</h4>
                  <h4>RS : {{product.price}}</h4>

               </div>
              </div>
          </div>
          {% endfor %}
      </div>
      <div class="mx-auto">
          {% if products.paginator.num_pages > 1 %}

          <hr>
          <div class="text-center">
              {% for pg in products.paginator.page_range %}
              <a href="?page={{pg}}" class="btn btn-light bt-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
          </div>
          {% endif %}
      </div>
      <br>

  </div>
{% endblock %}

ecommerce/templates/demo.html
<html>
<head>
  <title>hh</title>
  <body>
<p> demo</p>
</body>
</head>
</html>

ecommerce/templates/footer.html
<div class="footer-navbar-fixed-bottom foot">
    <p class="text-center"><b>©</b>digital mart pvt ltd.All rights reserved</p>
</div>

ecommerce/templates/header.html
{% load static %}<br>
<header>
    <center>
        <a href="{% url 'ecomapp:allprodcat' %}"><img src="{% static 'img/logoo.png' %}"></a>
    </center>
</header><br>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'ecomapp:allprodcat' %}"><i class="fa fa-house"></i> home</a>
      </li>
      <li class="nav-item dropdown {% if 'ecomapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-shop"></i>shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">allproduct</a>
          {% for i in links %}
          <a class="dropdown-item" href="{{ i.get_url }}">{{i.name}}</a>
          {% endfor %}
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-cart-shopping"></i>{{item_count}}</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:searchresult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>


    </form>
  </div>
</nav>
<br>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
  {% if category %}
    {{product.name}}- digital mart

  {% endif %}
{% endblock %}

{% block body %}

  <div class="row my_prod_row_class">
      <div class="mx_auto">
          <p><a href="{% url 'ecomapp:allprodcat' %}">home</a>|<a href="{{Product.category.get_url}}">{{Product.category}}</a>|{{Product.name}}</p>

      </div>
  </div>
<br>

<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
       <img class="img" src ="{{Product.image.url}}" alt="{{product.name}}" width="75%">

               </div>
            </div>

<div>
            </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <h1 class="my_prd_title">{{Product.name}}</h1>
        <p><b>₹{{Product.price}}</b></p>
        <p class="text-justify">{{Product.description}}</p>
        {% if Product.stock <= 0 %}
        <p class="text-justify">out of stock</p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' Product.id %}">add to cart</a>
        {% endif %}

</div>
</div>
</div>


{% endblock %}

ecommerce/templates/scratches.html
  </div>
    {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

</div>





  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


  <i class="fa fa-cart-shopping"></i>


    <a href="cart_item.Product.get_absolute_url">



        <div class="row my_row_class">
        <div class="mx_auto">

                https://kit.fontawesome.com/a076d05399.js
                <script src="https://kit.fontawesome.com/a076d05399.js"></script>

                                https://kit.fontawesome.com/162dba6519.js
                               <script src="https://kit.fontawesome.com/cf2b91a915.js crossmargin"="anonymous"></script>


<link rel="stylesheet" href="https://kit.fontawesome.com/21c419a9db.css" crossorigin="anonymous">
            <script src="https://kit.fontawesome.com/21c419a9db.js" crossorigin="anonymous"></script>

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    variety of digital products
{% endblock %}
{% block title %}
product
{% endblock %}
{% block body %}
<div>
    <p class="text-center my_search"> you have searched for <b>"{{query}}"</b></p>
</div>
<div class="container">
      <div class="row">
      {% for product in products %}
      <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
          <div class="card h-100 text-center" style="min-width:18rem;">
               <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}"></a>
              <div class="card-body ">
                  <h4>{{product.name}}</h4>
                  <h4>{{product.price}}</h4>

               </div>
              </div>
          </div>
        {% empty %}
          <div class="row mx-auto">
              <p class="text-center">0 result found </p>
          </div>
          {% endfor %}
      </div>
</div>






{% endblock %}